# Slick Enterprises HQ - developer convenience targets
COMPOSE := docker compose -f infra/docker/docker-compose.yml

.PHONY: help up down build logs ps restart migrate revision seed health ui-dev gateway-dev fmt test clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'

up: ## Build + start the full stack in the background
	$(COMPOSE) up -d --build

down: ## Stop the stack
	$(COMPOSE) down

build: ## Build all images
	$(COMPOSE) build

logs: ## Tail logs for all services
	$(COMPOSE) logs -f --tail=100

ps: ## Show container status
	$(COMPOSE) ps

restart: ## Restart the stack
	$(COMPOSE) restart

migrate: ## Apply Alembic database migrations
	$(COMPOSE) run --rm slick-gateway alembic upgrade head

revision: ## Create a new autogenerated migration (NAME="message")
	$(COMPOSE) run --rm slick-gateway alembic revision --autogenerate -m "$(NAME)"

seed: ## Seed the example business compartment + agents
	$(COMPOSE) run --rm slick-gateway python -m gateway.seed

health: ## Curl the gateway health endpoint
	curl -s http://localhost:8000/health | python3 -m json.tool

ui-dev: ## Run the Next.js UI locally (outside docker)
	cd apps/ui && npm install && npm run dev

gateway-dev: ## Run the gateway locally (outside docker)
	cd apps/gateway && pip install -e ../../packages/shared && pip install -r requirements.txt && uvicorn gateway.main:app --reload

fmt: ## Format Python (ruff) and JS (prettier) where available
	-ruff format .
	-cd apps/ui && npx prettier --write .

test: ## Run Python tests
	$(COMPOSE) run --rm slick-gateway pytest -q

clean: ## Stop stack and remove volumes (DESTRUCTIVE: deletes db/redis data)
	$(COMPOSE) down -v
