"""Initial schema.

Creates all tables defined in `slick_shared.models`. For the v1 scaffold we build the
schema directly from the ORM metadata so it always matches the models. Future schema
changes should use normal autogenerated revisions (`make revision NAME="..."`).

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-13
"""

from __future__ import annotations

from alembic import op

from slick_shared.db import Base
from slick_shared import models  # noqa: F401  (register models on metadata)

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
